package com.xinluhuang.englishlearn.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xinluhuang.englishlearn.greendao.entity.CET4Word;
import com.xinluhuang.englishlearn.greendao.entity.CET6Word;
import com.xinluhuang.englishlearn.greendao.entity.Example;
import com.xinluhuang.englishlearn.greendao.entity.MarkWord;
import com.xinluhuang.englishlearn.greendao.entity.Meaning;
import com.xinluhuang.englishlearn.greendao.entity.SearchWord;
import com.xinluhuang.englishlearn.greendao.entity.Word;

import com.xinluhuang.englishlearn.greendao.dao.CET4WordDao;
import com.xinluhuang.englishlearn.greendao.dao.CET6WordDao;
import com.xinluhuang.englishlearn.greendao.dao.ExampleDao;
import com.xinluhuang.englishlearn.greendao.dao.MarkWordDao;
import com.xinluhuang.englishlearn.greendao.dao.MeaningDao;
import com.xinluhuang.englishlearn.greendao.dao.SearchWordDao;
import com.xinluhuang.englishlearn.greendao.dao.WordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cET4WordDaoConfig;
    private final DaoConfig cET6WordDaoConfig;
    private final DaoConfig exampleDaoConfig;
    private final DaoConfig markWordDaoConfig;
    private final DaoConfig meaningDaoConfig;
    private final DaoConfig searchWordDaoConfig;
    private final DaoConfig wordDaoConfig;

    private final CET4WordDao cET4WordDao;
    private final CET6WordDao cET6WordDao;
    private final ExampleDao exampleDao;
    private final MarkWordDao markWordDao;
    private final MeaningDao meaningDao;
    private final SearchWordDao searchWordDao;
    private final WordDao wordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cET4WordDaoConfig = daoConfigMap.get(CET4WordDao.class).clone();
        cET4WordDaoConfig.initIdentityScope(type);

        cET6WordDaoConfig = daoConfigMap.get(CET6WordDao.class).clone();
        cET6WordDaoConfig.initIdentityScope(type);

        exampleDaoConfig = daoConfigMap.get(ExampleDao.class).clone();
        exampleDaoConfig.initIdentityScope(type);

        markWordDaoConfig = daoConfigMap.get(MarkWordDao.class).clone();
        markWordDaoConfig.initIdentityScope(type);

        meaningDaoConfig = daoConfigMap.get(MeaningDao.class).clone();
        meaningDaoConfig.initIdentityScope(type);

        searchWordDaoConfig = daoConfigMap.get(SearchWordDao.class).clone();
        searchWordDaoConfig.initIdentityScope(type);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        cET4WordDao = new CET4WordDao(cET4WordDaoConfig, this);
        cET6WordDao = new CET6WordDao(cET6WordDaoConfig, this);
        exampleDao = new ExampleDao(exampleDaoConfig, this);
        markWordDao = new MarkWordDao(markWordDaoConfig, this);
        meaningDao = new MeaningDao(meaningDaoConfig, this);
        searchWordDao = new SearchWordDao(searchWordDaoConfig, this);
        wordDao = new WordDao(wordDaoConfig, this);

        registerDao(CET4Word.class, cET4WordDao);
        registerDao(CET6Word.class, cET6WordDao);
        registerDao(Example.class, exampleDao);
        registerDao(MarkWord.class, markWordDao);
        registerDao(Meaning.class, meaningDao);
        registerDao(SearchWord.class, searchWordDao);
        registerDao(Word.class, wordDao);
    }
    
    public void clear() {
        cET4WordDaoConfig.clearIdentityScope();
        cET6WordDaoConfig.clearIdentityScope();
        exampleDaoConfig.clearIdentityScope();
        markWordDaoConfig.clearIdentityScope();
        meaningDaoConfig.clearIdentityScope();
        searchWordDaoConfig.clearIdentityScope();
        wordDaoConfig.clearIdentityScope();
    }

    public CET4WordDao getCET4WordDao() {
        return cET4WordDao;
    }

    public CET6WordDao getCET6WordDao() {
        return cET6WordDao;
    }

    public ExampleDao getExampleDao() {
        return exampleDao;
    }

    public MarkWordDao getMarkWordDao() {
        return markWordDao;
    }

    public MeaningDao getMeaningDao() {
        return meaningDao;
    }

    public SearchWordDao getSearchWordDao() {
        return searchWordDao;
    }

    public WordDao getWordDao() {
        return wordDao;
    }

}
