package com.xinluhuang.englishlearn.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xinluhuang.englishlearn.greendao.entity.Example;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "dict_collins_example".
*/
public class ExampleDao extends AbstractDao<Example, Void> {

    public static final String TABLENAME = "dict_collins_example";

    /**
     * Properties of entity Example.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Mid = new Property(0, int.class, "mid", false, "mid");
        public final static Property En = new Property(1, String.class, "en", false, "en");
        public final static Property Cn = new Property(2, String.class, "cn", false, "cn");
    }


    public ExampleDao(DaoConfig config) {
        super(config);
    }
    
    public ExampleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"dict_collins_example\" (" + //
                "\"mid\" INTEGER NOT NULL ," + // 0: mid
                "\"en\" TEXT," + // 1: en
                "\"cn\" TEXT);"); // 2: cn
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"dict_collins_example\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Example entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getMid());
 
        String en = entity.getEn();
        if (en != null) {
            stmt.bindString(2, en);
        }
 
        String cn = entity.getCn();
        if (cn != null) {
            stmt.bindString(3, cn);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Example entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getMid());
 
        String en = entity.getEn();
        if (en != null) {
            stmt.bindString(2, en);
        }
 
        String cn = entity.getCn();
        if (cn != null) {
            stmt.bindString(3, cn);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Example readEntity(Cursor cursor, int offset) {
        Example entity = new Example( //
            cursor.getInt(offset + 0), // mid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // en
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // cn
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Example entity, int offset) {
        entity.setMid(cursor.getInt(offset + 0));
        entity.setEn(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCn(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Example entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Example entity) {
        return null;
    }

    @Override
    public boolean hasKey(Example entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
